repos:
-   repo: https://github.com/psf/black
    rev: '23.3.0'  # pick a git hash / tag to point to
    hooks:
    -   id: black
        language_version: python3.8  # or the minimum Python version you support

-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings]

